const apps = [
  { label: "OMS", value: "oms" },
  { label: "UMS", value: "ums" },
  { label: "LMS", value: "lms" },
  { label: "IMS", value: "ims" },
  { label: "Common", value: "common" },
  { label: "Middleware", value: "middleware" },
  { label: "Kart", value: "kart" },
  { label: "Payment", value: "payment" },
  { label: "Achieve", value: "achieve" },
  { label: "STMS", value: "stms" },
  { label: "Mentoring", value: "mentoring" },
  { label: "POMS", value: "poms" },
  { label: "SOS", value: "sos" },
  { label: "FMS", value: "fms" },
  { label: "WMS", value: "wms" },
  { label: "CXMS", value: "cxms" },
  { label: "SCAchieve", value: "scachieve" },
  { label: "SCOS", value: "scos" },
  { label: "Counselling", value: "counselling" },
  { label: "UXAchieve", value: "uxachieve" },
  { label: "MOS", value: "mos" },
  { label: "DFOS", value: "dfos" },
  { label: "DFAchieve", value: "dfachieve" },
  { label: "STMS", value: "stms" },
  { label: "Compliance", value: "compliance" },
];

const modules = [
  { label: "LMS Loan Creation", value: "lms_loan_creation" },
  { label: "LMS Nach", value: "lms_nach" },
  { label: "LMS Collection", value: "lms_collection" },
  { label: "LMS Foreclosure", value: "lms_foreclosure" },
  { label: "LMS Manual Payment", value: "lms_manual_payment" },
  { label: "OMS Order Creation", value: "oms_order_creation" },
  { label: "OMS Inventory Creation", value: "oms_inventory_creation" },
  { label: "OMS Sku", value: "oms_sku" },
  { label: "OMS Cashback", value: "oms_cashback" },
  { label: "PMS Finance Reconciliation", value: "pms_finance_reconciliation" },
  { label: "POMS Batch Upload", value: "poms_batch_upload" },
  { label: "POMS Byjus Classes Batch", value: "poms_byjus_classes_batch" },
  { label: "UMS Employee Creation", value: "ums_employee_creation" },
  { label: "UMS Employee Validation", value: "ums_employee_validation" },
  { label: "UMS Attendance", value: "ums_attendance" },
  { label: "FMS Payment Report", value: "fms_payment_report" },
  { label: "FMS Invoice", value: "fms_invoice" },
  { label: "FMS Reconcilation Report", value: "fms_reconcilation_report" },
];

module.exports = {
  apps,
  modules,
};
