// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-south-1',
  aws_cognito_identity_pool_id:
    'ap-south-1:56b1f3aa-47fb-4308-b58f-ac0010b26129',
  aws_cognito_region: 'ap-south-1',
  aws_user_pools_id: 'ap-south-1_Z12CpShDW',
  aws_user_pools_web_client_id: '5tnm1g4ka04mqid308q7bct87r'
};

export default awsmobile;
