name: master-client-code-deploy-to-vercel
on: 
  push:
    branches:
      - master
    paths:
      - client/**
      
jobs:
  #build:
    #runs-on: ubuntu-latest
    #steps:
     # - uses: actions/checkout@v2 
     # - uses: actions/setup-node@v2
     #   with:
     #     node-version: '14.x'
     # - run: npm install
     # - run: npm run build 
  
  deploy:
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: vercel-deployment
        with:
          #github-token: ${{ secrets.GH_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
          vercel-project-name: 'microservices-achieve'
    #outputs:
      #preview-url: ${{ steps.vercel-deployment.outputs.preview-url }}
      
  #lighthouse:
   # runs-on: ubuntu-latest
   # needs: deploy
   # steps:
     # - uses: actions/checkout@v2
    #  - name: Run Lighthouse on urls and validate with lighthouserc
    #    uses: treosh/lighthouse-ci-action@v7
      #  with:
    #      urls: |
      #      ${{ needs.deploy.outputs.preview-url }}
     #       ${{ needs.deploy.outputs.preview-url }}
       #   budgetPath: ./budget.json
      #    runs: 3  
